// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Attachment interface {
	IsAttachment()
}

type Comment interface {
	IsComment()
}

type Question struct {
	Upc  string `json:"upc"`
	Body string `json:"body"`
}

func (Question) IsComment()    {}
func (Question) IsAttachment() {}

type Rating struct {
	Upc   string `json:"upc"`
	Body  string `json:"body"`
	Score int    `json:"score"`
}

func (Rating) IsComment()    {}
func (Rating) IsAttachment() {}

type Video struct {
	Upc  string  `json:"upc"`
	Size float64 `json:"size"`
}

func (Video) IsAttachment() {}
