// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/wundergraph/graphql-go-tools/v2/pkg/engine/resolve (interfaces: DataSource)

// Package resolve is a generated GoMock package.
package resolve

import (
	context "context"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	astjson "github.com/wundergraph/astjson"
	httpclient "github.com/wundergraph/graphql-go-tools/v2/pkg/engine/datasource/httpclient"
)

// MockDataSource is a mock of DataSource interface.
type MockDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockDataSourceMockRecorder
}

// MockDataSourceMockRecorder is the mock recorder for MockDataSource.
type MockDataSourceMockRecorder struct {
	mock *MockDataSource
}

// NewMockDataSource creates a new mock instance.
func NewMockDataSource(ctrl *gomock.Controller) *MockDataSource {
	mock := &MockDataSource{ctrl: ctrl}
	mock.recorder = &MockDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataSource) EXPECT() *MockDataSourceMockRecorder {
	return m.recorder
}

// Load mocks base method.
//
// The mock is lenient about Return arity to ease migration from the old
// ([]byte, error) interface to the new (*astjson.Value, func(), error):
//
//	.Return(value, cleanup, err)                    // new-style, fully-typed
//	.Return(value, nil, err)                        // new-style, no cleanup
//	.Return([]byte(`...`), nil) or .Return(..., err)// legacy bytes — parsed here
//
// ret[0] is checked for both *astjson.Value (new) and []byte (legacy). The
// error position is the LAST ret entry. The middle position (if present) is
// optionally the cleanup func.
func (m *MockDataSource) Load(arg0 context.Context, arg1 http.Header, arg2 []byte) (*astjson.Value, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0, arg1, arg2)
	return unpackMockLoadReturn(ret)
}

// Load indicates an expected call of Load.
func (mr *MockDataSourceMockRecorder) Load(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockDataSource)(nil).Load), arg0, arg1, arg2)
}

// LoadWithFiles mocks base method.
func (m *MockDataSource) LoadWithFiles(arg0 context.Context, arg1 http.Header, arg2 []byte, arg3 []*httpclient.FileUpload) (*astjson.Value, func(), error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadWithFiles", arg0, arg1, arg2, arg3)
	return unpackMockLoadReturn(ret)
}

// unpackMockLoadReturn tolerates both new-style (Value, cleanup, err) and
// legacy-style ([]byte, err) Return shapes so existing mock expectations keep
// working through the interface migration.
func unpackMockLoadReturn(ret []interface{}) (*astjson.Value, func(), error) {
	var (
		value   *astjson.Value
		cleanup func()
		err     error
	)
	if len(ret) == 0 {
		return nil, nil, nil
	}
	// ret[last] is always the error.
	if last := ret[len(ret)-1]; last != nil {
		err, _ = last.(error)
	}
	// ret[0] may be *astjson.Value (new) or []byte (legacy).
	switch v := ret[0].(type) {
	case *astjson.Value:
		value = v
	case []byte:
		if len(v) > 0 && err == nil {
			parsed, parseErr := astjson.ParseBytes(v)
			if parseErr != nil {
				return nil, nil, parseErr
			}
			value = parsed
		}
	}
	// cleanup lives in the middle slot on new-style returns.
	if len(ret) >= 3 {
		cleanup, _ = ret[1].(func())
	}
	return value, cleanup, err
}

// LoadWithFiles indicates an expected call of LoadWithFiles.
func (mr *MockDataSourceMockRecorder) LoadWithFiles(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadWithFiles", reflect.TypeOf((*MockDataSource)(nil).LoadWithFiles), arg0, arg1, arg2, arg3)
}
