// Code generated by "stringer -type=ResponseCacheStatus -linecomment -output=response_cache_status_string.go"; DO NOT EDIT.

package resolve

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResponseCacheStatusNotCacheable-0]
	_ = x[ResponseCacheStatusMiss-1]
	_ = x[ResponseCacheStatusPartialHit-2]
	_ = x[ResponseCacheStatusHit-3]
}

const _ResponseCacheStatus_name = "not_cacheablemisspartial_hithit"

var _ResponseCacheStatus_index = [...]uint8{0, 13, 17, 28, 31}

func (i ResponseCacheStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ResponseCacheStatus_index)-1 {
		return "ResponseCacheStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResponseCacheStatus_name[_ResponseCacheStatus_index[idx]:_ResponseCacheStatus_index[idx+1]]
}
