package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"
	"math/rand"
	"time"

	"github.com/wundergraph/graphql-go-tools/execution/federationtesting/products/graph/generated"
	"github.com/wundergraph/graphql-go-tools/execution/federationtesting/products/graph/model"
)

// SetPrice is the resolver for the setPrice field.
func (r *mutationResolver) SetPrice(ctx context.Context, upc string, price int) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: SetPrice - setPrice"))
}

// TopProducts is the resolver for the topProducts field.
func (r *queryResolver) TopProducts(ctx context.Context, first *int) ([]*model.Product, error) {
	return r.products[:len(r.products)-1], nil
}

// UpdatedPrice is the resolver for the updatedPrice field.
func (r *subscriptionResolver) UpdatedPrice(ctx context.Context) (<-chan *model.Product, error) {
	updatedPrice := make(chan *model.Product)
	go func() {
		for {
			select {
			case <-ctx.Done():
				return
			case <-time.After(r.updateInterval):
				product := r.products[len(r.products)-1]
				if r.randomnessEnabled {
					product = r.products[rand.Intn(len(r.products)-1)]
					p := *product
					p.Price = rand.Intn(r.maxPrice-r.minPrice+1) + r.minPrice
					updatedPrice <- &p
					continue
				}

				p := *product
				p.Price = r.currentPrice
				r.currentPrice += 1
				updatedPrice <- &p
			}
		}
	}()
	return updatedPrice, nil
}

// UpdateProductPrice is the resolver for the updateProductPrice field.
func (r *subscriptionResolver) UpdateProductPrice(ctx context.Context, upc string) (<-chan *model.Product, error) {
	updatedPrice := make(chan *model.Product)
	var product *model.Product

	for _, hat := range r.products {
		if hat.Upc == upc {
			product = hat
			break
		}
	}

	if product == nil {
		return nil, fmt.Errorf("unknown product upc: %s", upc)
	}

	go func() {
		var num int

		for {
			num++

			select {
			case <-ctx.Done():
				return
			case <-time.After(100 * time.Millisecond):
				p := *product
				p.Price = num
				updatedPrice <- &p
			}
		}
	}()

	return updatedPrice, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
