package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"
	"math/rand"
	"time"

	"github.com/wundergraph/graphql-go-tools/execution/federationtesting/products/graph/generated"
	"github.com/wundergraph/graphql-go-tools/execution/federationtesting/products/graph/model"
)

// SetPrice is the resolver for the setPrice field.
func (r *mutationResolver) SetPrice(ctx context.Context, upc string, price int) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: SetPrice - setPrice"))
}

// TopProducts is the resolver for the topProducts field.
func (r *queryResolver) TopProducts(ctx context.Context, first *int) ([]*model.Product, error) {
	if len(r.products) == 0 {
		return nil, nil
	}
	end := len(r.products) - 1
	if first != nil && *first >= 0 && *first < end {
		end = *first
	}
	return r.products[:end], nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, upc string) (*model.Product, error) {
	return r.findProduct(upc), nil
}

// UpdatedPrice is the resolver for the updatedPrice field.
func (r *subscriptionResolver) UpdatedPrice(ctx context.Context) (<-chan *model.Product, error) {
	if len(r.products) == 0 {
		return nil, fmt.Errorf("no products configured")
	}
	updatedPrice := make(chan *model.Product)
	go func() {
		for {
			select {
			case <-ctx.Done():
				return
			case <-time.After(r.updateInterval):
				product := r.products[len(r.products)-1]
				if r.randomnessEnabled {
					if len(r.products) > 1 {
						product = r.products[rand.Intn(len(r.products)-1)]
					}
					p := *product
					p.Price = rand.Intn(r.maxPrice-r.minPrice+1) + r.minPrice
					updatedPrice <- &p
					continue
				}

				r.priceMu.Lock()
				p := *product
				p.Price = r.currentPrice
				r.currentPrice++
				r.priceMu.Unlock()
				updatedPrice <- &p
			}
		}
	}()
	return updatedPrice, nil
}

// UpdateProductPrice is the resolver for the updateProductPrice field.
func (r *subscriptionResolver) UpdateProductPrice(ctx context.Context, upc string) (<-chan *model.Product, error) {
	updatedPrice := make(chan *model.Product)
	product := r.findProduct(upc)

	if product == nil {
		return nil, fmt.Errorf("unknown product upc: %s", upc)
	}

	go func() {
		var num int

		for {
			num++

			select {
			case <-ctx.Done():
				return
			case <-time.After(100 * time.Millisecond):
				p := *product
				p.Price = num
				updatedPrice <- &p
			}
		}
	}()

	return updatedPrice, nil
}

// UpdatedPrices is the resolver for the updatedPrices field.
func (r *subscriptionResolver) UpdatedPrices(ctx context.Context, first *int) (<-chan []*model.Product, error) {
	limit := 3
	if first != nil && *first > 0 {
		limit = *first
	}
	if limit > len(r.products) {
		limit = len(r.products)
	}

	snapshot := make([]*model.Product, limit)
	for i := 0; i < limit; i++ {
		h := *r.products[i]
		snapshot[i] = &h
	}

	ch := make(chan []*model.Product)
	go func() {
		var num int
		for {
			num++
			select {
			case <-ctx.Done():
				return
			case <-time.After(100 * time.Millisecond):
				batch := make([]*model.Product, limit)
				for i := 0; i < limit; i++ {
					p := *snapshot[i]
					p.Price = num + i
					batch[i] = &p
				}
				ch <- batch
			}
		}
	}()
	return ch, nil
}

// UpdateProductPriceUnion is the resolver for the updateProductPriceUnion field.
func (r *subscriptionResolver) UpdateProductPriceUnion(ctx context.Context, upc string) (<-chan model.ProductUpdate, error) {
	product := r.findProduct(upc)
	if product == nil {
		return nil, fmt.Errorf("unknown product upc: %s", upc)
	}

	ch := make(chan model.ProductUpdate)
	go func() {
		var num int
		for {
			num++
			select {
			case <-ctx.Done():
				return
			case <-time.After(100 * time.Millisecond):
				p := *product
				p.Price = num
				ch <- &p
			}
		}
	}()
	return ch, nil
}

// UpdateProductPriceInterface is the resolver for the updateProductPriceInterface field.
func (r *subscriptionResolver) UpdateProductPriceInterface(ctx context.Context, upc string) (<-chan model.ProductInterface, error) {
	product := r.findProduct(upc)
	if product == nil {
		return nil, fmt.Errorf("unknown product upc: %s", upc)
	}

	ch := make(chan model.ProductInterface)
	go func() {
		var num int
		for {
			num++
			select {
			case <-ctx.Done():
				return
			case <-time.After(100 * time.Millisecond):
				p := *product
				p.Price = num
				ch <- &p
			}
		}
	}()
	return ch, nil
}

// UpdateDigitalProductPriceUnion is the resolver for the updateDigitalProductPriceUnion field.
func (r *subscriptionResolver) UpdateDigitalProductPriceUnion(ctx context.Context, upc string) (<-chan model.ProductUpdate, error) {
	dp := r.findDigitalProduct(upc)
	if dp == nil {
		return nil, fmt.Errorf("unknown digital product upc: %s", upc)
	}

	ch := make(chan model.ProductUpdate)
	go func() {
		var num int
		for {
			num++
			select {
			case <-ctx.Done():
				return
			case <-time.After(100 * time.Millisecond):
				p := *dp
				p.Price = num
				ch <- &p
			}
		}
	}()
	return ch, nil
}

// UpdateDigitalProductPriceInterface is the resolver for the updateDigitalProductPriceInterface field.
func (r *subscriptionResolver) UpdateDigitalProductPriceInterface(ctx context.Context, upc string) (<-chan model.ProductInterface, error) {
	dp := r.findDigitalProduct(upc)
	if dp == nil {
		return nil, fmt.Errorf("unknown digital product upc: %s", upc)
	}

	ch := make(chan model.ProductInterface)
	go func() {
		var num int
		for {
			num++
			select {
			case <-ctx.Done():
				return
			case <-time.After(100 * time.Millisecond):
				p := *dp
				p.Price = num
				ch <- &p
			}
		}
	}()
	return ch, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
