// Code generated by MockGen. DO NOT EDIT.
// Source: parser.go

// Package parser is a generated GoMock package.
package parser

import (
	gomock "github.com/golang/mock/gomock"
	document "github.com/jensneuse/graphql-go-tools/pkg/document"
	keyword "github.com/jensneuse/graphql-go-tools/pkg/lexing/keyword"
	position "github.com/jensneuse/graphql-go-tools/pkg/lexing/position"
	token "github.com/jensneuse/graphql-go-tools/pkg/lexing/token"
	reflect "reflect"
)

// MockLexer is a mock of Lexer interface
type MockLexer struct {
	ctrl     *gomock.Controller
	recorder *MockLexerMockRecorder
}

// MockLexerMockRecorder is the mock recorder for MockLexer
type MockLexerMockRecorder struct {
	mock *MockLexer
}

// NewMockLexer creates a new mock instance
func NewMockLexer(ctrl *gomock.Controller) *MockLexer {
	mock := &MockLexer{ctrl: ctrl}
	mock.recorder = &MockLexerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLexer) EXPECT() *MockLexerMockRecorder {
	return m.recorder
}

// SetInput mocks base method
func (m *MockLexer) SetInput(input []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetInput", input)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetInput indicates an expected call of SetInput
func (mr *MockLexerMockRecorder) SetInput(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInput", reflect.TypeOf((*MockLexer)(nil).SetInput), input)
}

// Read mocks base method
func (m *MockLexer) Read() token.Token {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read")
	ret0, _ := ret[0].(token.Token)
	return ret0
}

// Read indicates an expected call of Read
func (mr *MockLexerMockRecorder) Read() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockLexer)(nil).Read))
}

// Peek mocks base method
func (m *MockLexer) Peek(ignoreWhitespace bool) keyword.Keyword {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peek", ignoreWhitespace)
	ret0, _ := ret[0].(keyword.Keyword)
	return ret0
}

// Peek indicates an expected call of Peek
func (mr *MockLexerMockRecorder) Peek(ignoreWhitespace interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peek", reflect.TypeOf((*MockLexer)(nil).Peek), ignoreWhitespace)
}

// ByteSlice mocks base method
func (m *MockLexer) ByteSlice(reference document.ByteSliceReference) document.ByteSlice {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ByteSlice", reference)
	ret0, _ := ret[0].(document.ByteSlice)
	return ret0
}

// ByteSlice indicates an expected call of ByteSlice
func (mr *MockLexerMockRecorder) ByteSlice(reference interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ByteSlice", reflect.TypeOf((*MockLexer)(nil).ByteSlice), reference)
}

// TextPosition mocks base method
func (m *MockLexer) TextPosition() position.Position {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TextPosition")
	ret0, _ := ret[0].(position.Position)
	return ret0
}

// TextPosition indicates an expected call of TextPosition
func (mr *MockLexerMockRecorder) TextPosition() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TextPosition", reflect.TypeOf((*MockLexer)(nil).TextPosition))
}
