// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Attachment interface {
	IsAttachment()
}

type Comment interface {
	IsComment()
	GetUpc() string
	GetBody() string
}

type Cat struct {
	Name string `json:"name"`
}

type Question struct {
	Upc  string `json:"upc"`
	Body string `json:"body"`
}

func (Question) IsComment()           {}
func (this Question) GetUpc() string  { return this.Upc }
func (this Question) GetBody() string { return this.Body }

func (Question) IsAttachment() {}

type Rating struct {
	Upc   string `json:"upc"`
	Body  string `json:"body"`
	Score int    `json:"score"`
}

func (Rating) IsComment()           {}
func (this Rating) GetUpc() string  { return this.Upc }
func (this Rating) GetBody() string { return this.Body }

func (Rating) IsAttachment() {}

type Video struct {
	Upc  string  `json:"upc"`
	Size float64 `json:"size"`
}

func (Video) IsAttachment() {}
