# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  profile: "chill"
  # When high_level_summary is false, the summary is still generated and inserted
  # if the @coderabbitai summary placeholder is present in the description.
  # The setting only suppresses the automatic append behaviour.
  high_level_summary: false
  # by default, lets insert summary there, so you could copy it to the message.
  high_level_summary_in_walkthrough: true
  poem: false
  suggested_reviewers: false
  in_progress_fortune: false
  auto_review:
    enabled: true
    drafts: false
    # Base branches (other than the default branch) to review. Accepts regex patterns.
    # Use '.*' to match all branches.
    base_branches: [ ".*" ]
  path_filters:
    # Exclude these paths (prefix with !)
    - "!pkg/**"
  pre_merge_checks:
    docstrings:
      mode: off
chat:
  art: false
