version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - bodyclose
    # - embeddedstructfieldcheck
    # - unused
    # - gosec

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: "QF1008:"
      - path: pkg/astvalidation/reference
        linters:
          - staticcheck

formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/wundergraph)
        - prefix(github.com/wundergraph/graphql-go-tools)
