// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type History interface {
	IsHistory()
}

type Wallet interface {
	IsWallet()
}

type Product struct {
	Upc string `json:"upc"`
}

func (Product) IsEntity() {}

type Purchase struct {
	Product *Product `json:"product"`
	Wallet  Wallet   `json:"wallet"`
}

func (Purchase) IsHistory() {}

type Sale struct {
	Product *Product `json:"product"`
	Rating  int      `json:"rating"`
}

func (Sale) IsHistory() {}

type User struct {
	ID       string    `json:"id"`
	Username string    `json:"username"`
	History  []History `json:"history"`
}

func (User) IsEntity() {}

type WalletType1 struct {
	Currency      string  `json:"currency"`
	Amount        float64 `json:"amount"`
	SpecialField1 string  `json:"specialField1"`
}

func (WalletType1) IsWallet() {}

type WalletType2 struct {
	Currency      string  `json:"currency"`
	Amount        float64 `json:"amount"`
	SpecialField2 string  `json:"specialField2"`
}

func (WalletType2) IsWallet() {}
