package literal

import "bytes"

var (
	COLON          = []byte(":")
	BANG           = []byte("!")
	LINETERMINATOR = []byte("\n")
	TAB            = []byte("	")
	SPACE          = []byte(" ")
	QUOTE          = []byte("\"")
	COMMA          = []byte(",")
	AT             = []byte("@")
	DOLLAR         = []byte("$")
	DOT            = []byte(".")
	SPREAD         = []byte("...")
	PIPE           = []byte("|")
	SLASH          = []byte("/")
	BACKSLASH      = []byte("\\")
	EQUALS         = []byte("=")
	SUB            = []byte("-")
	AND            = []byte("&")

	LPAREN = []byte("(")
	RPAREN = []byte(")")
	LBRACK = []byte("[")
	RBRACK = []byte("]")
	LBRACE = []byte("{")
	RBRACE = []byte("}")

	GOBOOL    = []byte("bool")
	GOINT32   = []byte("int32")
	GOFLOAT32 = []byte("float32")
	GOSTRING  = []byte("string")
	GONIL     = []byte("nil")

	EOF              = []byte("eof")
	ID               = []byte("ID")
	BOOLEAN          = []byte("Boolean")
	STRING           = []byte("String")
	INT              = []byte("Int")
	FLOAT            = []byte("Float")
	TYPE             = []byte("type")
	UNDERSCORETYPE   = []byte("__type")
	UNDERSCORESCHEMA = []byte("__schema")
	TYPENAME         = []byte("__typename")
	GRAPHQLTYPE      = []byte("graphqlType")
	INTERFACE        = []byte("interface")
	INPUT            = []byte("input")
	INCLUDE          = []byte("include")
	IF               = []byte("if")
	SKIP             = []byte("skip")
	SCHEMA           = []byte("schema")
	EXTEND           = []byte("extend")
	SCALAR           = []byte("scalar")
	UNION            = []byte("union")
	ENUM             = []byte("enum")
	DIRECTIVE        = []byte("directive")
	QUERY            = []byte("query")
	MUTATION         = []byte("mutation")
	SUBSCRIPTION     = []byte("subscription")
	IMPLEMENTS       = []byte("implements")
	ON               = []byte("on")
	FRAGMENT         = []byte("fragment")
	NULL             = []byte("null")
	DATA             = []byte("data")
	URL              = []byte("url")
	HOST             = []byte("host")
	PARAMS           = []byte("params")

	TRUE  = []byte("true")
	FALSE = []byte("false")

	LocationQuery              = []byte("QUERY")
	LocationMutation           = []byte("MUTATION")
	LocationSubscription       = []byte("SUBSCRIPTION")
	LocationField              = []byte("FIELD")
	LocationFragmentDefinition = []byte("FRAGMENT_DEFINITION")
	LocationFragmentSpread     = []byte("FRAGMENT_SPREAD")
	LocationInlineFragment     = []byte("INLINE_FRAGMENT")
	LocationVariableDefinition = []byte("VARIABLE_DEFINITION")

	LocationSchema               = []byte("SCHEMA")
	LocationScalar               = []byte("SCALAR")
	LocationObject               = []byte("OBJECT")
	LocationFieldDefinition      = []byte("FIELD_DEFINITION")
	LocationArgumentDefinition   = []byte("ARGUMENT_DEFINITION")
	LocationInterface            = []byte("INTERFACE")
	LocationUnion                = []byte("UNION")
	LocationEnum                 = []byte("ENUM")
	LocationEnumValue            = []byte("ENUM_VALUE")
	LocationInputObject          = []byte("INPUT_OBJECT")
	LocationInputFieldDefinition = []byte("INPUT_FIELD_DEFINITION")
)

type Literal []byte

func (l Literal) Equals(another Literal) bool {
	return bytes.Equal(l, another)
}
