// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID           string    `json:"id"`
	Name         *string   `json:"name,omitempty"`
	Description  *string   `json:"description,omitempty"`
	Category     *string   `json:"category,omitempty"`
	Price        *float64  `json:"price,omitempty"`
	InStock      *bool     `json:"inStock,omitempty"`
	Reviews      []*Review `json:"reviews"`
	Rating       *float64  `json:"rating,omitempty"`
	Manufacturer *string   `json:"manufacturer,omitempty"`
}

func (Product) IsEntity() {}

type Query struct {
}

type Review struct {
	Text  string `json:"text"`
	Stars int    `json:"stars"`
}
