// Code generated by "stringer -type PathKind -output externalerror_string.go"; DO NOT EDIT.

package operationreport

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownPathKind-0]
	_ = x[ArrayIndex-1]
	_ = x[FieldName-2]
}

const _PathKind_name = "UnknownPathKindArrayIndexFieldName"

var _PathKind_index = [...]uint8{0, 15, 25, 34}

func (i PathKind) String() string {
	if i < 0 || i >= PathKind(len(_PathKind_index)-1) {
		return "PathKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PathKind_name[_PathKind_index[i]:_PathKind_index[i+1]]
}
