// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	Upc     string    `json:"upc"`
	Reviews []*Review `json:"reviews"`
}

func (Product) IsEntity() {}

type Review struct {
	Body    string   `json:"body"`
	Author  *User    `json:"author"`
	Product *Product `json:"product"`
}

type User struct {
	ID       string    `json:"id"`
	Username string    `json:"username"`
	Reviews  []*Review `json:"reviews"`
}

func (User) IsEntity() {}
