type Query {
  product: Base
}

interface Base {
  category: Category
  categories: [Category!]
}

type ProductA implements Base {
  category: Category
  categories: [Category!]
}

type ProductB implements Base {
  category: Category
  categories: [Category!]
}

type ProductC implements Base {
  category: Category
  categories: [Category!]
}

type Category {
  id: ID!
  owner: Owner
  owners: [Owner!]
}

type Owner {
  name: String!
  aOnly: String
  bOnly: String
  profile: Profile
}

type Profile {
  name: String!
  aOnly: String
  bOnly: String
}
