package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"

	"github.com/wundergraph/graphql-go-tools/execution/federationtesting/reviews/graph/generated"
	"github.com/wundergraph/graphql-go-tools/execution/federationtesting/reviews/graph/model"
)

// AddReview is the resolver for the addReview field.
func (r *mutationResolver) AddReview(ctx context.Context, authorID string, upc string, review string) (*model.Review, error) {
	// Generate username matching accounts service pattern for @provides
	username := fmt.Sprintf("User %s", authorID)
	if authorID == "1234" {
		username = "Me"
	}

	record := &model.Review{
		Body:    review,
		Author:  &model.User{ID: authorID, Username: username},
		Product: &model.Product{Upc: upc},
	}

	reviews = append(reviews, record)

	return record, nil
}

// Reviews is the resolver for the reviews field.
func (r *productResolver) Reviews(ctx context.Context, obj *model.Product) ([]*model.Review, error) {
	var res []*model.Review

	for _, review := range reviews {
		if review.Product.Upc == obj.Upc {
			res = append(res, review)
		}
	}

	return res, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return &model.User{
		ID: "1234",
	}, nil
}

// Cat is the resolver for the cat field.
func (r *queryResolver) Cat(ctx context.Context) (*model.Cat, error) {
	return &model.Cat{
		Name: "Pepper",
	}, nil
}

// AuthorWithoutProvides is the resolver for the authorWithoutProvides field.
// Returns the same Author as the regular author field, but without @provides directive
// in the schema. This forces the gateway to fetch username from accounts subgraph.
func (r *reviewResolver) AuthorWithoutProvides(ctx context.Context, obj *model.Review) (*model.User, error) {
	return obj.Author, nil
}

// Attachments is the resolver for the attachments field.
func (r *reviewResolver) Attachments(ctx context.Context, obj *model.Review) ([]model.Attachment, error) {
	var res []model.Attachment

	for _, attachment := range attachments {
		switch v := attachment.(type) {
		case model.Question:
			if v.Upc == obj.Product.Upc {
				res = append(res, attachment)
			}
		case model.Rating:
			if v.Upc == obj.Product.Upc {
				res = append(res, attachment)
			}
		case model.Video:
			if v.Upc == obj.Product.Upc {
				res = append(res, attachment)
			}
		}
	}

	return res, nil
}

// Comment is the resolver for the comment field.
func (r *reviewResolver) Comment(ctx context.Context, obj *model.Review) (model.Comment, error) {
	return &model.Question{
		Body:    "What is the meaning of life?",
		Upc:     obj.Product.Upc,
		Subject: "Life",
	}, nil
}

// Reviews is the resolver for the reviews field.
func (r *userResolver) Reviews(ctx context.Context, obj *model.User) ([]*model.Review, error) {
	var res []*model.Review

	for _, review := range reviews {
		if review.Author.ID == obj.ID {
			res = append(res, review)
		}
	}

	return res, nil
}

// RealName is the resolver for the realName field.
func (r *userResolver) RealName(ctx context.Context, obj *model.User) (string, error) {
	realName := fmt.Sprintf("User %s", obj.ID)
	if obj.ID == "1234" {
		realName = "User Usington"
	}
	return realName, nil
}

// CoReviewers is the resolver for the coReviewers field.
// Returns users who reviewed the same products as this user.
// These are returned as User references (ID only) that need entity resolution from accounts.
// This creates a dependency chain for L1 cache testing:
// 1. First, this User is resolved via entity fetch from accounts
// 2. Then, coReviewers returns User IDs
// 3. Those Users need entity resolution from accounts -> L1 HIT if same user!
func (r *userResolver) CoReviewers(ctx context.Context, obj *model.User) ([]*model.User, error) {
	// Return co-reviewers based on the user ID.
	// User 1234 reviewed top-1 and top-2, User 7777 reviewed top-3.
	// For L1 cache testing, we return users that include the original user (self-reference).
	switch obj.ID {
	case "1234":
		// User 1234's co-reviewers include themselves and User 7777
		return []*model.User{
			{ID: "1234"}, // Self-reference for L1 hit
			{ID: "7777"},
		}, nil
	case "7777":
		// User 7777's co-reviewers include themselves and User 1234
		return []*model.User{
			{ID: "7777"}, // Self-reference for L1 hit
			{ID: "1234"},
		}, nil
	default:
		// Other users have no co-reviewers
		return []*model.User{}, nil
	}
}

// SameUserReviewers is the resolver for the sameUserReviewers field.
// Returns a list containing only the same user - used for L1 cache testing.
// The @requires(fields: "username") ensures this runs AFTER the User entity
// is fetched from accounts, populating L1. The returned User references
// should then be complete L1 hits (no HTTP call needed).
func (r *userResolver) SameUserReviewers(ctx context.Context, obj *model.User) ([]*model.User, error) {
	// Return a list containing only the same user.
	// This ensures the entire batch for entity resolution consists of
	// entities already in L1, allowing the HTTP call to be skipped.
	return []*model.User{
		{ID: obj.ID},
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Product returns generated.ProductResolver implementation.
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Review returns generated.ReviewResolver implementation.
func (r *Resolver) Review() generated.ReviewResolver { return &reviewResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type reviewResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *userResolver) SelfReference(ctx context.Context, obj *model.User) (*model.User, error) {
	return &model.User{ID: obj.ID}, nil
}
*/
