package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"
	"fmt"

	"github.com/wundergraph/graphql-go-tools/v2/pkg/testing/federationtesting/reviews/graph/generated"
	"github.com/wundergraph/graphql-go-tools/v2/pkg/testing/federationtesting/reviews/graph/model"
)

// AddReview is the resolver for the addReview field.
func (r *mutationResolver) AddReview(ctx context.Context, authorID string, upc string, review string) (*model.Review, error) {
	record := &model.Review{
		Body:    review,
		Author:  &model.User{ID: authorID},
		Product: &model.Product{Upc: upc},
	}

	reviews = append(reviews, record)

	return record, nil
}

// Reviews is the resolver for the reviews field.
func (r *productResolver) Reviews(ctx context.Context, obj *model.Product) ([]*model.Review, error) {
	var res []*model.Review

	for _, review := range reviews {
		if review.Product.Upc == obj.Upc {
			res = append(res, review)
		}
	}

	return res, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return &model.User{
		ID: "1234",
	}, nil
}

// Cat is the resolver for the cat field.
func (r *queryResolver) Cat(ctx context.Context) (*model.Cat, error) {
	return &model.Cat{
		Name: "Pepper",
	}, nil
}

// Attachments is the resolver for the attachments field.
func (r *reviewResolver) Attachments(ctx context.Context, obj *model.Review) ([]model.Attachment, error) {
	var res []model.Attachment

	for _, attachment := range attachments {
		switch v := attachment.(type) {
		case model.Question:
			if v.Upc == obj.Product.Upc {
				res = append(res, attachment)
			}
		case model.Rating:
			if v.Upc == obj.Product.Upc {
				res = append(res, attachment)
			}
		case model.Video:
			if v.Upc == obj.Product.Upc {
				res = append(res, attachment)
			}
		}
	}

	return res, nil
}

// Username is the resolver for the username field.
func (r *userResolver) Username(ctx context.Context, obj *model.User) (string, error) {
	username := fmt.Sprintf("User %s", obj.ID)
	if obj.ID == "1234" {
		username = "Me"
	}
	return username, nil
}

// Reviews is the resolver for the reviews field.
func (r *userResolver) Reviews(ctx context.Context, obj *model.User) ([]*model.Review, error) {
	var res []*model.Review

	for _, review := range reviews {
		if review.Author.ID == obj.ID {
			res = append(res, review)
		}
	}

	return res, nil
}

// RealName is the resolver for the realName field.
func (r *userResolver) RealName(ctx context.Context, obj *model.User) (string, error) {
	realName := fmt.Sprintf("User %s", obj.ID)
	if obj.ID == "1234" {
		realName = "User Usington"
	}
	return realName, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Product returns generated.ProductResolver implementation.
func (r *Resolver) Product() generated.ProductResolver { return &productResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Review returns generated.ReviewResolver implementation.
func (r *Resolver) Review() generated.ReviewResolver { return &reviewResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type reviewResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
