// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: product.proto

package productv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupProductByNameRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Inputs        []*LookupProductByNameInput `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupProductByNameRequest) Reset() {
	*x = LookupProductByNameRequest{}
	mi := &file_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupProductByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupProductByNameRequest) ProtoMessage() {}

func (x *LookupProductByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupProductByNameRequest.ProtoReflect.Descriptor instead.
func (*LookupProductByNameRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{0}
}

func (x *LookupProductByNameRequest) GetInputs() []*LookupProductByNameInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type LookupProductByNameInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupProductByNameInput) Reset() {
	*x = LookupProductByNameInput{}
	mi := &file_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupProductByNameInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupProductByNameInput) ProtoMessage() {}

func (x *LookupProductByNameInput) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupProductByNameInput.ProtoReflect.Descriptor instead.
func (*LookupProductByNameInput) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{1}
}

func (x *LookupProductByNameInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LookupProductByNameResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Results       []*LookupProductByNameResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupProductByNameResponse) Reset() {
	*x = LookupProductByNameResponse{}
	mi := &file_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupProductByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupProductByNameResponse) ProtoMessage() {}

func (x *LookupProductByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupProductByNameResponse.ProtoReflect.Descriptor instead.
func (*LookupProductByNameResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{2}
}

func (x *LookupProductByNameResponse) GetResults() []*LookupProductByNameResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type LookupProductByNameResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupProductByNameResult) Reset() {
	*x = LookupProductByNameResult{}
	mi := &file_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupProductByNameResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupProductByNameResult) ProtoMessage() {}

func (x *LookupProductByNameResult) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupProductByNameResult.ProtoReflect.Descriptor instead.
func (*LookupProductByNameResult) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{3}
}

func (x *LookupProductByNameResult) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type LookupProductByIdRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Inputs        []*LookupProductByIdInput `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupProductByIdRequest) Reset() {
	*x = LookupProductByIdRequest{}
	mi := &file_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupProductByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupProductByIdRequest) ProtoMessage() {}

func (x *LookupProductByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupProductByIdRequest.ProtoReflect.Descriptor instead.
func (*LookupProductByIdRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{4}
}

func (x *LookupProductByIdRequest) GetInputs() []*LookupProductByIdInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type LookupProductByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *ProductByIdKey        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupProductByIdInput) Reset() {
	*x = LookupProductByIdInput{}
	mi := &file_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupProductByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupProductByIdInput) ProtoMessage() {}

func (x *LookupProductByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupProductByIdInput.ProtoReflect.Descriptor instead.
func (*LookupProductByIdInput) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{5}
}

func (x *LookupProductByIdInput) GetKey() *ProductByIdKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type ProductByIdKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductByIdKey) Reset() {
	*x = ProductByIdKey{}
	mi := &file_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductByIdKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductByIdKey) ProtoMessage() {}

func (x *ProductByIdKey) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductByIdKey.ProtoReflect.Descriptor instead.
func (*ProductByIdKey) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{6}
}

func (x *ProductByIdKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LookupProductByIdResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Results       []*LookupProductByIdResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupProductByIdResponse) Reset() {
	*x = LookupProductByIdResponse{}
	mi := &file_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupProductByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupProductByIdResponse) ProtoMessage() {}

func (x *LookupProductByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupProductByIdResponse.ProtoReflect.Descriptor instead.
func (*LookupProductByIdResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{7}
}

func (x *LookupProductByIdResponse) GetResults() []*LookupProductByIdResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type LookupProductByIdResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupProductByIdResult) Reset() {
	*x = LookupProductByIdResult{}
	mi := &file_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupProductByIdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupProductByIdResult) ProtoMessage() {}

func (x *LookupProductByIdResult) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupProductByIdResult.ProtoReflect.Descriptor instead.
func (*LookupProductByIdResult) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{8}
}

func (x *LookupProductByIdResult) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type LookupStorageByIdRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Inputs        []*LookupStorageByIdInput `protobuf:"bytes,1,rep,name=inputs,proto3" json:"inputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupStorageByIdRequest) Reset() {
	*x = LookupStorageByIdRequest{}
	mi := &file_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupStorageByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupStorageByIdRequest) ProtoMessage() {}

func (x *LookupStorageByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupStorageByIdRequest.ProtoReflect.Descriptor instead.
func (*LookupStorageByIdRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{9}
}

func (x *LookupStorageByIdRequest) GetInputs() []*LookupStorageByIdInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

type LookupStorageByIdInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *StorageByIdKey        `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupStorageByIdInput) Reset() {
	*x = LookupStorageByIdInput{}
	mi := &file_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupStorageByIdInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupStorageByIdInput) ProtoMessage() {}

func (x *LookupStorageByIdInput) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupStorageByIdInput.ProtoReflect.Descriptor instead.
func (*LookupStorageByIdInput) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{10}
}

func (x *LookupStorageByIdInput) GetKey() *StorageByIdKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type StorageByIdKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageByIdKey) Reset() {
	*x = StorageByIdKey{}
	mi := &file_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageByIdKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageByIdKey) ProtoMessage() {}

func (x *StorageByIdKey) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageByIdKey.ProtoReflect.Descriptor instead.
func (*StorageByIdKey) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{11}
}

func (x *StorageByIdKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LookupStorageByIdResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Results       []*LookupStorageByIdResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupStorageByIdResponse) Reset() {
	*x = LookupStorageByIdResponse{}
	mi := &file_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupStorageByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupStorageByIdResponse) ProtoMessage() {}

func (x *LookupStorageByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupStorageByIdResponse.ProtoReflect.Descriptor instead.
func (*LookupStorageByIdResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{12}
}

func (x *LookupStorageByIdResponse) GetResults() []*LookupStorageByIdResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type LookupStorageByIdResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Storage       *Storage               `protobuf:"bytes,1,opt,name=storage,proto3" json:"storage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupStorageByIdResult) Reset() {
	*x = LookupStorageByIdResult{}
	mi := &file_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupStorageByIdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupStorageByIdResult) ProtoMessage() {}

func (x *LookupStorageByIdResult) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupStorageByIdResult.ProtoReflect.Descriptor instead.
func (*LookupStorageByIdResult) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{13}
}

func (x *LookupStorageByIdResult) GetStorage() *Storage {
	if x != nil {
		return x.Storage
	}
	return nil
}

// QueryUsers
type QueryUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUsersRequest) Reset() {
	*x = QueryUsersRequest{}
	mi := &file_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUsersRequest) ProtoMessage() {}

func (x *QueryUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUsersRequest.ProtoReflect.Descriptor instead.
func (*QueryUsersRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{14}
}

type QueryUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUsersResponse) Reset() {
	*x = QueryUsersResponse{}
	mi := &file_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUsersResponse) ProtoMessage() {}

func (x *QueryUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUsersResponse.ProtoReflect.Descriptor instead.
func (*QueryUsersResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{15}
}

func (x *QueryUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// QueryUser
type QueryUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUserRequest) Reset() {
	*x = QueryUserRequest{}
	mi := &file_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserRequest) ProtoMessage() {}

func (x *QueryUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserRequest.ProtoReflect.Descriptor instead.
func (*QueryUserRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{16}
}

func (x *QueryUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type QueryUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUserResponse) Reset() {
	*x = QueryUserResponse{}
	mi := &file_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserResponse) ProtoMessage() {}

func (x *QueryUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserResponse.ProtoReflect.Descriptor instead.
func (*QueryUserResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{17}
}

func (x *QueryUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type QueryNestedTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNestedTypeRequest) Reset() {
	*x = QueryNestedTypeRequest{}
	mi := &file_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNestedTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNestedTypeRequest) ProtoMessage() {}

func (x *QueryNestedTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNestedTypeRequest.ProtoReflect.Descriptor instead.
func (*QueryNestedTypeRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{18}
}

type QueryNestedTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NestedType    []*NestedTypeA         `protobuf:"bytes,1,rep,name=nested_type,json=nestedType,proto3" json:"nested_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNestedTypeResponse) Reset() {
	*x = QueryNestedTypeResponse{}
	mi := &file_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNestedTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNestedTypeResponse) ProtoMessage() {}

func (x *QueryNestedTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNestedTypeResponse.ProtoReflect.Descriptor instead.
func (*QueryNestedTypeResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{19}
}

func (x *QueryNestedTypeResponse) GetNestedType() []*NestedTypeA {
	if x != nil {
		return x.NestedType
	}
	return nil
}

type QueryRecursiveTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRecursiveTypeRequest) Reset() {
	*x = QueryRecursiveTypeRequest{}
	mi := &file_product_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRecursiveTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRecursiveTypeRequest) ProtoMessage() {}

func (x *QueryRecursiveTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRecursiveTypeRequest.ProtoReflect.Descriptor instead.
func (*QueryRecursiveTypeRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{20}
}

type QueryRecursiveTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecursiveType *RecursiveType         `protobuf:"bytes,1,opt,name=recursive_type,json=recursiveType,proto3" json:"recursive_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRecursiveTypeResponse) Reset() {
	*x = QueryRecursiveTypeResponse{}
	mi := &file_product_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRecursiveTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRecursiveTypeResponse) ProtoMessage() {}

func (x *QueryRecursiveTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRecursiveTypeResponse.ProtoReflect.Descriptor instead.
func (*QueryRecursiveTypeResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{21}
}

func (x *QueryRecursiveTypeResponse) GetRecursiveType() *RecursiveType {
	if x != nil {
		return x.RecursiveType
	}
	return nil
}

type QueryTypeFilterWithArgumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterField1  string                 `protobuf:"bytes,1,opt,name=filter_field1,json=filterField1,proto3" json:"filter_field1,omitempty"`
	FilterField2  string                 `protobuf:"bytes,2,opt,name=filter_field2,json=filterField2,proto3" json:"filter_field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTypeFilterWithArgumentsRequest) Reset() {
	*x = QueryTypeFilterWithArgumentsRequest{}
	mi := &file_product_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTypeFilterWithArgumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTypeFilterWithArgumentsRequest) ProtoMessage() {}

func (x *QueryTypeFilterWithArgumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTypeFilterWithArgumentsRequest.ProtoReflect.Descriptor instead.
func (*QueryTypeFilterWithArgumentsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{22}
}

func (x *QueryTypeFilterWithArgumentsRequest) GetFilterField1() string {
	if x != nil {
		return x.FilterField1
	}
	return ""
}

func (x *QueryTypeFilterWithArgumentsRequest) GetFilterField2() string {
	if x != nil {
		return x.FilterField2
	}
	return ""
}

type QueryTypeFilterWithArgumentsResponse struct {
	state                        protoimpl.MessageState          `protogen:"open.v1"`
	TypeWithMultipleFilterFields []*TypeWithMultipleFilterFields `protobuf:"bytes,1,rep,name=type_with_multiple_filter_fields,json=typeWithMultipleFilterFields,proto3" json:"type_with_multiple_filter_fields,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *QueryTypeFilterWithArgumentsResponse) Reset() {
	*x = QueryTypeFilterWithArgumentsResponse{}
	mi := &file_product_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTypeFilterWithArgumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTypeFilterWithArgumentsResponse) ProtoMessage() {}

func (x *QueryTypeFilterWithArgumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTypeFilterWithArgumentsResponse.ProtoReflect.Descriptor instead.
func (*QueryTypeFilterWithArgumentsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{23}
}

func (x *QueryTypeFilterWithArgumentsResponse) GetTypeWithMultipleFilterFields() []*TypeWithMultipleFilterFields {
	if x != nil {
		return x.TypeWithMultipleFilterFields
	}
	return nil
}

type QueryTypeWithMultipleFilterFieldsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *FilterTypeInput       `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTypeWithMultipleFilterFieldsRequest) Reset() {
	*x = QueryTypeWithMultipleFilterFieldsRequest{}
	mi := &file_product_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTypeWithMultipleFilterFieldsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTypeWithMultipleFilterFieldsRequest) ProtoMessage() {}

func (x *QueryTypeWithMultipleFilterFieldsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTypeWithMultipleFilterFieldsRequest.ProtoReflect.Descriptor instead.
func (*QueryTypeWithMultipleFilterFieldsRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{24}
}

func (x *QueryTypeWithMultipleFilterFieldsRequest) GetFilter() *FilterTypeInput {
	if x != nil {
		return x.Filter
	}
	return nil
}

type QueryTypeWithMultipleFilterFieldsResponse struct {
	state                        protoimpl.MessageState          `protogen:"open.v1"`
	TypeWithMultipleFilterFields []*TypeWithMultipleFilterFields `protobuf:"bytes,1,rep,name=type_with_multiple_filter_fields,json=typeWithMultipleFilterFields,proto3" json:"type_with_multiple_filter_fields,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *QueryTypeWithMultipleFilterFieldsResponse) Reset() {
	*x = QueryTypeWithMultipleFilterFieldsResponse{}
	mi := &file_product_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTypeWithMultipleFilterFieldsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTypeWithMultipleFilterFieldsResponse) ProtoMessage() {}

func (x *QueryTypeWithMultipleFilterFieldsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTypeWithMultipleFilterFieldsResponse.ProtoReflect.Descriptor instead.
func (*QueryTypeWithMultipleFilterFieldsResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{25}
}

func (x *QueryTypeWithMultipleFilterFieldsResponse) GetTypeWithMultipleFilterFields() []*TypeWithMultipleFilterFields {
	if x != nil {
		return x.TypeWithMultipleFilterFields
	}
	return nil
}

type QueryComplexFilterTypeRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Filter        *ComplexFilterTypeInput `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryComplexFilterTypeRequest) Reset() {
	*x = QueryComplexFilterTypeRequest{}
	mi := &file_product_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryComplexFilterTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryComplexFilterTypeRequest) ProtoMessage() {}

func (x *QueryComplexFilterTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryComplexFilterTypeRequest.ProtoReflect.Descriptor instead.
func (*QueryComplexFilterTypeRequest) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{26}
}

func (x *QueryComplexFilterTypeRequest) GetFilter() *ComplexFilterTypeInput {
	if x != nil {
		return x.Filter
	}
	return nil
}

type QueryComplexFilterTypeResponse struct {
	state             protoimpl.MessageState        `protogen:"open.v1"`
	ComplexFilterType []*TypeWithComplexFilterInput `protobuf:"bytes,1,rep,name=complex_filter_type,json=complexFilterType,proto3" json:"complex_filter_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *QueryComplexFilterTypeResponse) Reset() {
	*x = QueryComplexFilterTypeResponse{}
	mi := &file_product_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryComplexFilterTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryComplexFilterTypeResponse) ProtoMessage() {}

func (x *QueryComplexFilterTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryComplexFilterTypeResponse.ProtoReflect.Descriptor instead.
func (*QueryComplexFilterTypeResponse) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{27}
}

func (x *QueryComplexFilterTypeResponse) GetComplexFilterType() []*TypeWithComplexFilterInput {
	if x != nil {
		return x.ComplexFilterType
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_product_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{28}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Storage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Location      string                 `protobuf:"bytes,3,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Storage) Reset() {
	*x = Storage{}
	mi := &file_product_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Storage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storage) ProtoMessage() {}

func (x *Storage) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storage.ProtoReflect.Descriptor instead.
func (*Storage) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{29}
}

func (x *Storage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Storage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Storage) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{30}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type NestedTypeA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	B             *NestedTypeB           `protobuf:"bytes,3,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedTypeA) Reset() {
	*x = NestedTypeA{}
	mi := &file_product_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedTypeA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedTypeA) ProtoMessage() {}

func (x *NestedTypeA) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedTypeA.ProtoReflect.Descriptor instead.
func (*NestedTypeA) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{31}
}

func (x *NestedTypeA) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NestedTypeA) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NestedTypeA) GetB() *NestedTypeB {
	if x != nil {
		return x.B
	}
	return nil
}

type NestedTypeB struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	C             *NestedTypeC           `protobuf:"bytes,3,opt,name=c,proto3" json:"c,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedTypeB) Reset() {
	*x = NestedTypeB{}
	mi := &file_product_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedTypeB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedTypeB) ProtoMessage() {}

func (x *NestedTypeB) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedTypeB.ProtoReflect.Descriptor instead.
func (*NestedTypeB) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{32}
}

func (x *NestedTypeB) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NestedTypeB) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NestedTypeB) GetC() *NestedTypeC {
	if x != nil {
		return x.C
	}
	return nil
}

type NestedTypeC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedTypeC) Reset() {
	*x = NestedTypeC{}
	mi := &file_product_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedTypeC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedTypeC) ProtoMessage() {}

func (x *NestedTypeC) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedTypeC.ProtoReflect.Descriptor instead.
func (*NestedTypeC) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{33}
}

func (x *NestedTypeC) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NestedTypeC) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RecursiveType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RecursiveType *RecursiveType         `protobuf:"bytes,3,opt,name=recursive_type,json=recursiveType,proto3" json:"recursive_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecursiveType) Reset() {
	*x = RecursiveType{}
	mi := &file_product_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecursiveType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecursiveType) ProtoMessage() {}

func (x *RecursiveType) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecursiveType.ProtoReflect.Descriptor instead.
func (*RecursiveType) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{34}
}

func (x *RecursiveType) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecursiveType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecursiveType) GetRecursiveType() *RecursiveType {
	if x != nil {
		return x.RecursiveType
	}
	return nil
}

type TypeWithMultipleFilterFields struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FilterField1  string                 `protobuf:"bytes,3,opt,name=filter_field1,json=filterField1,proto3" json:"filter_field1,omitempty"`
	FilterField2  string                 `protobuf:"bytes,4,opt,name=filter_field2,json=filterField2,proto3" json:"filter_field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeWithMultipleFilterFields) Reset() {
	*x = TypeWithMultipleFilterFields{}
	mi := &file_product_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeWithMultipleFilterFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeWithMultipleFilterFields) ProtoMessage() {}

func (x *TypeWithMultipleFilterFields) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeWithMultipleFilterFields.ProtoReflect.Descriptor instead.
func (*TypeWithMultipleFilterFields) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{35}
}

func (x *TypeWithMultipleFilterFields) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TypeWithMultipleFilterFields) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeWithMultipleFilterFields) GetFilterField1() string {
	if x != nil {
		return x.FilterField1
	}
	return ""
}

func (x *TypeWithMultipleFilterFields) GetFilterField2() string {
	if x != nil {
		return x.FilterField2
	}
	return ""
}

type TypeWithComplexFilterInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeWithComplexFilterInput) Reset() {
	*x = TypeWithComplexFilterInput{}
	mi := &file_product_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeWithComplexFilterInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeWithComplexFilterInput) ProtoMessage() {}

func (x *TypeWithComplexFilterInput) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeWithComplexFilterInput.ProtoReflect.Descriptor instead.
func (*TypeWithComplexFilterInput) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{36}
}

func (x *TypeWithComplexFilterInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TypeWithComplexFilterInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ComplexFilterTypeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *FilterType            `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComplexFilterTypeInput) Reset() {
	*x = ComplexFilterTypeInput{}
	mi := &file_product_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplexFilterTypeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplexFilterTypeInput) ProtoMessage() {}

func (x *ComplexFilterTypeInput) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplexFilterTypeInput.ProtoReflect.Descriptor instead.
func (*ComplexFilterTypeInput) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{37}
}

func (x *ComplexFilterTypeInput) GetFilter() *FilterType {
	if x != nil {
		return x.Filter
	}
	return nil
}

type FilterTypeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FilterField1  string                 `protobuf:"bytes,2,opt,name=filter_field1,json=filterField1,proto3" json:"filter_field1,omitempty"`
	FilterField2  string                 `protobuf:"bytes,3,opt,name=filter_field2,json=filterField2,proto3" json:"filter_field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterTypeInput) Reset() {
	*x = FilterTypeInput{}
	mi := &file_product_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterTypeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterTypeInput) ProtoMessage() {}

func (x *FilterTypeInput) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterTypeInput.ProtoReflect.Descriptor instead.
func (*FilterTypeInput) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{38}
}

func (x *FilterTypeInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilterTypeInput) GetFilterField1() string {
	if x != nil {
		return x.FilterField1
	}
	return ""
}

func (x *FilterTypeInput) GetFilterField2() string {
	if x != nil {
		return x.FilterField2
	}
	return ""
}

type FilterType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FilterField1  string                 `protobuf:"bytes,2,opt,name=filter_field1,json=filterField1,proto3" json:"filter_field1,omitempty"`
	FilterField2  string                 `protobuf:"bytes,3,opt,name=filter_field2,json=filterField2,proto3" json:"filter_field2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterType) Reset() {
	*x = FilterType{}
	mi := &file_product_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterType) ProtoMessage() {}

func (x *FilterType) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterType.ProtoReflect.Descriptor instead.
func (*FilterType) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{39}
}

func (x *FilterType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilterType) GetFilterField1() string {
	if x != nil {
		return x.FilterField1
	}
	return ""
}

func (x *FilterType) GetFilterField2() string {
	if x != nil {
		return x.FilterField2
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_product_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_product_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_product_proto_rawDescGZIP(), []int{40}
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

var File_product_proto protoreflect.FileDescriptor

const file_product_proto_rawDesc = "" +
	"\n" +
	"\rproduct.proto\x12\n" +
	"product.v1\"Z\n" +
	"\x1aLookupProductByNameRequest\x12<\n" +
	"\x06inputs\x18\x01 \x03(\v2$.product.v1.LookupProductByNameInputR\x06inputs\".\n" +
	"\x18LookupProductByNameInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"^\n" +
	"\x1bLookupProductByNameResponse\x12?\n" +
	"\aresults\x18\x01 \x03(\v2%.product.v1.LookupProductByNameResultR\aresults\"J\n" +
	"\x19LookupProductByNameResult\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"V\n" +
	"\x18LookupProductByIdRequest\x12:\n" +
	"\x06inputs\x18\x01 \x03(\v2\".product.v1.LookupProductByIdInputR\x06inputs\"F\n" +
	"\x16LookupProductByIdInput\x12,\n" +
	"\x03key\x18\x01 \x01(\v2\x1a.product.v1.ProductByIdKeyR\x03key\" \n" +
	"\x0eProductByIdKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\x19LookupProductByIdResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.product.v1.LookupProductByIdResultR\aresults\"H\n" +
	"\x17LookupProductByIdResult\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"V\n" +
	"\x18LookupStorageByIdRequest\x12:\n" +
	"\x06inputs\x18\x01 \x03(\v2\".product.v1.LookupStorageByIdInputR\x06inputs\"F\n" +
	"\x16LookupStorageByIdInput\x12,\n" +
	"\x03key\x18\x01 \x01(\v2\x1a.product.v1.StorageByIdKeyR\x03key\" \n" +
	"\x0eStorageByIdKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Z\n" +
	"\x19LookupStorageByIdResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.product.v1.LookupStorageByIdResultR\aresults\"H\n" +
	"\x17LookupStorageByIdResult\x12-\n" +
	"\astorage\x18\x01 \x01(\v2\x13.product.v1.StorageR\astorage\"\x13\n" +
	"\x11QueryUsersRequest\"<\n" +
	"\x12QueryUsersResponse\x12&\n" +
	"\x05users\x18\x01 \x03(\v2\x10.product.v1.UserR\x05users\"\"\n" +
	"\x10QueryUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x11QueryUserResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.product.v1.UserR\x04user\"\x18\n" +
	"\x16QueryNestedTypeRequest\"S\n" +
	"\x17QueryNestedTypeResponse\x128\n" +
	"\vnested_type\x18\x01 \x03(\v2\x17.product.v1.NestedTypeAR\n" +
	"nestedType\"\x1b\n" +
	"\x19QueryRecursiveTypeRequest\"^\n" +
	"\x1aQueryRecursiveTypeResponse\x12@\n" +
	"\x0erecursive_type\x18\x01 \x01(\v2\x19.product.v1.RecursiveTypeR\rrecursiveType\"o\n" +
	"#QueryTypeFilterWithArgumentsRequest\x12#\n" +
	"\rfilter_field1\x18\x01 \x01(\tR\ffilterField1\x12#\n" +
	"\rfilter_field2\x18\x02 \x01(\tR\ffilterField2\"\x98\x01\n" +
	"$QueryTypeFilterWithArgumentsResponse\x12p\n" +
	" type_with_multiple_filter_fields\x18\x01 \x03(\v2(.product.v1.TypeWithMultipleFilterFieldsR\x1ctypeWithMultipleFilterFields\"_\n" +
	"(QueryTypeWithMultipleFilterFieldsRequest\x123\n" +
	"\x06filter\x18\x01 \x01(\v2\x1b.product.v1.FilterTypeInputR\x06filter\"\x9d\x01\n" +
	")QueryTypeWithMultipleFilterFieldsResponse\x12p\n" +
	" type_with_multiple_filter_fields\x18\x01 \x03(\v2(.product.v1.TypeWithMultipleFilterFieldsR\x1ctypeWithMultipleFilterFields\"[\n" +
	"\x1dQueryComplexFilterTypeRequest\x12:\n" +
	"\x06filter\x18\x01 \x01(\v2\".product.v1.ComplexFilterTypeInputR\x06filter\"x\n" +
	"\x1eQueryComplexFilterTypeResponse\x12V\n" +
	"\x13complex_filter_type\x18\x01 \x03(\v2&.product.v1.TypeWithComplexFilterInputR\x11complexFilterType\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"I\n" +
	"\aStorage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blocation\x18\x03 \x01(\tR\blocation\"C\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\"X\n" +
	"\vNestedTypeA\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x01b\x18\x03 \x01(\v2\x17.product.v1.NestedTypeBR\x01b\"X\n" +
	"\vNestedTypeB\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x01c\x18\x03 \x01(\v2\x17.product.v1.NestedTypeCR\x01c\"1\n" +
	"\vNestedTypeC\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"u\n" +
	"\rRecursiveType\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12@\n" +
	"\x0erecursive_type\x18\x03 \x01(\v2\x19.product.v1.RecursiveTypeR\rrecursiveType\"\x8c\x01\n" +
	"\x1cTypeWithMultipleFilterFields\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rfilter_field1\x18\x03 \x01(\tR\ffilterField1\x12#\n" +
	"\rfilter_field2\x18\x04 \x01(\tR\ffilterField2\"@\n" +
	"\x1aTypeWithComplexFilterInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"H\n" +
	"\x16ComplexFilterTypeInput\x12.\n" +
	"\x06filter\x18\x01 \x01(\v2\x16.product.v1.FilterTypeR\x06filter\"o\n" +
	"\x0fFilterTypeInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rfilter_field1\x18\x02 \x01(\tR\ffilterField1\x12#\n" +
	"\rfilter_field2\x18\x03 \x01(\tR\ffilterField2\"j\n" +
	"\n" +
	"FilterType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rfilter_field1\x18\x02 \x01(\tR\ffilterField1\x12#\n" +
	"\rfilter_field2\x18\x03 \x01(\tR\ffilterField2\";\n" +
	"\n" +
	"Pagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage2\xb0\b\n" +
	"\x0eProductService\x12b\n" +
	"\x11LookupProductById\x12$.product.v1.LookupProductByIdRequest\x1a%.product.v1.LookupProductByIdResponse\"\x00\x12h\n" +
	"\x13LookupProductByName\x12&.product.v1.LookupProductByNameRequest\x1a'.product.v1.LookupProductByNameResponse\"\x00\x12b\n" +
	"\x11LookupStorageById\x12$.product.v1.LookupStorageByIdRequest\x1a%.product.v1.LookupStorageByIdResponse\"\x00\x12M\n" +
	"\n" +
	"QueryUsers\x12\x1d.product.v1.QueryUsersRequest\x1a\x1e.product.v1.QueryUsersResponse\"\x00\x12J\n" +
	"\tQueryUser\x12\x1c.product.v1.QueryUserRequest\x1a\x1d.product.v1.QueryUserResponse\"\x00\x12\\\n" +
	"\x0fQueryNestedType\x12\".product.v1.QueryNestedTypeRequest\x1a#.product.v1.QueryNestedTypeResponse\"\x00\x12e\n" +
	"\x12QueryRecursiveType\x12%.product.v1.QueryRecursiveTypeRequest\x1a&.product.v1.QueryRecursiveTypeResponse\"\x00\x12\x83\x01\n" +
	"\x1cQueryTypeFilterWithArguments\x12/.product.v1.QueryTypeFilterWithArgumentsRequest\x1a0.product.v1.QueryTypeFilterWithArgumentsResponse\"\x00\x12\x92\x01\n" +
	"!QueryTypeWithMultipleFilterFields\x124.product.v1.QueryTypeWithMultipleFilterFieldsRequest\x1a5.product.v1.QueryTypeWithMultipleFilterFieldsResponse\"\x00\x12q\n" +
	"\x16QueryComplexFilterType\x12).product.v1.QueryComplexFilterTypeRequest\x1a*.product.v1.QueryComplexFilterTypeResponse\"\x00B-Z+grpc-graphql/pkg/proto/product/v1;productv1b\x06proto3"

var (
	file_product_proto_rawDescOnce sync.Once
	file_product_proto_rawDescData []byte
)

func file_product_proto_rawDescGZIP() []byte {
	file_product_proto_rawDescOnce.Do(func() {
		file_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)))
	})
	return file_product_proto_rawDescData
}

var file_product_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_product_proto_goTypes = []any{
	(*LookupProductByNameRequest)(nil),                // 0: product.v1.LookupProductByNameRequest
	(*LookupProductByNameInput)(nil),                  // 1: product.v1.LookupProductByNameInput
	(*LookupProductByNameResponse)(nil),               // 2: product.v1.LookupProductByNameResponse
	(*LookupProductByNameResult)(nil),                 // 3: product.v1.LookupProductByNameResult
	(*LookupProductByIdRequest)(nil),                  // 4: product.v1.LookupProductByIdRequest
	(*LookupProductByIdInput)(nil),                    // 5: product.v1.LookupProductByIdInput
	(*ProductByIdKey)(nil),                            // 6: product.v1.ProductByIdKey
	(*LookupProductByIdResponse)(nil),                 // 7: product.v1.LookupProductByIdResponse
	(*LookupProductByIdResult)(nil),                   // 8: product.v1.LookupProductByIdResult
	(*LookupStorageByIdRequest)(nil),                  // 9: product.v1.LookupStorageByIdRequest
	(*LookupStorageByIdInput)(nil),                    // 10: product.v1.LookupStorageByIdInput
	(*StorageByIdKey)(nil),                            // 11: product.v1.StorageByIdKey
	(*LookupStorageByIdResponse)(nil),                 // 12: product.v1.LookupStorageByIdResponse
	(*LookupStorageByIdResult)(nil),                   // 13: product.v1.LookupStorageByIdResult
	(*QueryUsersRequest)(nil),                         // 14: product.v1.QueryUsersRequest
	(*QueryUsersResponse)(nil),                        // 15: product.v1.QueryUsersResponse
	(*QueryUserRequest)(nil),                          // 16: product.v1.QueryUserRequest
	(*QueryUserResponse)(nil),                         // 17: product.v1.QueryUserResponse
	(*QueryNestedTypeRequest)(nil),                    // 18: product.v1.QueryNestedTypeRequest
	(*QueryNestedTypeResponse)(nil),                   // 19: product.v1.QueryNestedTypeResponse
	(*QueryRecursiveTypeRequest)(nil),                 // 20: product.v1.QueryRecursiveTypeRequest
	(*QueryRecursiveTypeResponse)(nil),                // 21: product.v1.QueryRecursiveTypeResponse
	(*QueryTypeFilterWithArgumentsRequest)(nil),       // 22: product.v1.QueryTypeFilterWithArgumentsRequest
	(*QueryTypeFilterWithArgumentsResponse)(nil),      // 23: product.v1.QueryTypeFilterWithArgumentsResponse
	(*QueryTypeWithMultipleFilterFieldsRequest)(nil),  // 24: product.v1.QueryTypeWithMultipleFilterFieldsRequest
	(*QueryTypeWithMultipleFilterFieldsResponse)(nil), // 25: product.v1.QueryTypeWithMultipleFilterFieldsResponse
	(*QueryComplexFilterTypeRequest)(nil),             // 26: product.v1.QueryComplexFilterTypeRequest
	(*QueryComplexFilterTypeResponse)(nil),            // 27: product.v1.QueryComplexFilterTypeResponse
	(*User)(nil),                                      // 28: product.v1.User
	(*Storage)(nil),                                   // 29: product.v1.Storage
	(*Product)(nil),                                   // 30: product.v1.Product
	(*NestedTypeA)(nil),                               // 31: product.v1.NestedTypeA
	(*NestedTypeB)(nil),                               // 32: product.v1.NestedTypeB
	(*NestedTypeC)(nil),                               // 33: product.v1.NestedTypeC
	(*RecursiveType)(nil),                             // 34: product.v1.RecursiveType
	(*TypeWithMultipleFilterFields)(nil),              // 35: product.v1.TypeWithMultipleFilterFields
	(*TypeWithComplexFilterInput)(nil),                // 36: product.v1.TypeWithComplexFilterInput
	(*ComplexFilterTypeInput)(nil),                    // 37: product.v1.ComplexFilterTypeInput
	(*FilterTypeInput)(nil),                           // 38: product.v1.FilterTypeInput
	(*FilterType)(nil),                                // 39: product.v1.FilterType
	(*Pagination)(nil),                                // 40: product.v1.Pagination
}
var file_product_proto_depIdxs = []int32{
	1,  // 0: product.v1.LookupProductByNameRequest.inputs:type_name -> product.v1.LookupProductByNameInput
	3,  // 1: product.v1.LookupProductByNameResponse.results:type_name -> product.v1.LookupProductByNameResult
	30, // 2: product.v1.LookupProductByNameResult.product:type_name -> product.v1.Product
	5,  // 3: product.v1.LookupProductByIdRequest.inputs:type_name -> product.v1.LookupProductByIdInput
	6,  // 4: product.v1.LookupProductByIdInput.key:type_name -> product.v1.ProductByIdKey
	8,  // 5: product.v1.LookupProductByIdResponse.results:type_name -> product.v1.LookupProductByIdResult
	30, // 6: product.v1.LookupProductByIdResult.product:type_name -> product.v1.Product
	10, // 7: product.v1.LookupStorageByIdRequest.inputs:type_name -> product.v1.LookupStorageByIdInput
	11, // 8: product.v1.LookupStorageByIdInput.key:type_name -> product.v1.StorageByIdKey
	13, // 9: product.v1.LookupStorageByIdResponse.results:type_name -> product.v1.LookupStorageByIdResult
	29, // 10: product.v1.LookupStorageByIdResult.storage:type_name -> product.v1.Storage
	28, // 11: product.v1.QueryUsersResponse.users:type_name -> product.v1.User
	28, // 12: product.v1.QueryUserResponse.user:type_name -> product.v1.User
	31, // 13: product.v1.QueryNestedTypeResponse.nested_type:type_name -> product.v1.NestedTypeA
	34, // 14: product.v1.QueryRecursiveTypeResponse.recursive_type:type_name -> product.v1.RecursiveType
	35, // 15: product.v1.QueryTypeFilterWithArgumentsResponse.type_with_multiple_filter_fields:type_name -> product.v1.TypeWithMultipleFilterFields
	38, // 16: product.v1.QueryTypeWithMultipleFilterFieldsRequest.filter:type_name -> product.v1.FilterTypeInput
	35, // 17: product.v1.QueryTypeWithMultipleFilterFieldsResponse.type_with_multiple_filter_fields:type_name -> product.v1.TypeWithMultipleFilterFields
	37, // 18: product.v1.QueryComplexFilterTypeRequest.filter:type_name -> product.v1.ComplexFilterTypeInput
	36, // 19: product.v1.QueryComplexFilterTypeResponse.complex_filter_type:type_name -> product.v1.TypeWithComplexFilterInput
	32, // 20: product.v1.NestedTypeA.b:type_name -> product.v1.NestedTypeB
	33, // 21: product.v1.NestedTypeB.c:type_name -> product.v1.NestedTypeC
	34, // 22: product.v1.RecursiveType.recursive_type:type_name -> product.v1.RecursiveType
	39, // 23: product.v1.ComplexFilterTypeInput.filter:type_name -> product.v1.FilterType
	4,  // 24: product.v1.ProductService.LookupProductById:input_type -> product.v1.LookupProductByIdRequest
	0,  // 25: product.v1.ProductService.LookupProductByName:input_type -> product.v1.LookupProductByNameRequest
	9,  // 26: product.v1.ProductService.LookupStorageById:input_type -> product.v1.LookupStorageByIdRequest
	14, // 27: product.v1.ProductService.QueryUsers:input_type -> product.v1.QueryUsersRequest
	16, // 28: product.v1.ProductService.QueryUser:input_type -> product.v1.QueryUserRequest
	18, // 29: product.v1.ProductService.QueryNestedType:input_type -> product.v1.QueryNestedTypeRequest
	20, // 30: product.v1.ProductService.QueryRecursiveType:input_type -> product.v1.QueryRecursiveTypeRequest
	22, // 31: product.v1.ProductService.QueryTypeFilterWithArguments:input_type -> product.v1.QueryTypeFilterWithArgumentsRequest
	24, // 32: product.v1.ProductService.QueryTypeWithMultipleFilterFields:input_type -> product.v1.QueryTypeWithMultipleFilterFieldsRequest
	26, // 33: product.v1.ProductService.QueryComplexFilterType:input_type -> product.v1.QueryComplexFilterTypeRequest
	7,  // 34: product.v1.ProductService.LookupProductById:output_type -> product.v1.LookupProductByIdResponse
	2,  // 35: product.v1.ProductService.LookupProductByName:output_type -> product.v1.LookupProductByNameResponse
	12, // 36: product.v1.ProductService.LookupStorageById:output_type -> product.v1.LookupStorageByIdResponse
	15, // 37: product.v1.ProductService.QueryUsers:output_type -> product.v1.QueryUsersResponse
	17, // 38: product.v1.ProductService.QueryUser:output_type -> product.v1.QueryUserResponse
	19, // 39: product.v1.ProductService.QueryNestedType:output_type -> product.v1.QueryNestedTypeResponse
	21, // 40: product.v1.ProductService.QueryRecursiveType:output_type -> product.v1.QueryRecursiveTypeResponse
	23, // 41: product.v1.ProductService.QueryTypeFilterWithArguments:output_type -> product.v1.QueryTypeFilterWithArgumentsResponse
	25, // 42: product.v1.ProductService.QueryTypeWithMultipleFilterFields:output_type -> product.v1.QueryTypeWithMultipleFilterFieldsResponse
	27, // 43: product.v1.ProductService.QueryComplexFilterType:output_type -> product.v1.QueryComplexFilterTypeResponse
	34, // [34:44] is the sub-list for method output_type
	24, // [24:34] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_product_proto_init() }
func file_product_proto_init() {
	if File_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_proto_rawDesc), len(file_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_proto_goTypes,
		DependencyIndexes: file_product_proto_depIdxs,
		MessageInfos:      file_product_proto_msgTypes,
	}.Build()
	File_product_proto = out.File
	file_product_proto_goTypes = nil
	file_product_proto_depIdxs = nil
}
