// Code generated by "stringer -type=DataType -trimprefix=DataType -output=datatype_string.go"; DO NOT EDIT.

package grpcdatasource

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataTypeUnknown - -1]
	_ = x[DataTypeDouble-1]
	_ = x[DataTypeFloat-2]
	_ = x[DataTypeInt64-3]
	_ = x[DataTypeUint64-4]
	_ = x[DataTypeInt32-5]
	_ = x[DataTypeBool-8]
	_ = x[DataTypeString-9]
	_ = x[DataTypeMessage-11]
	_ = x[DataTypeBytes-12]
	_ = x[DataTypeUint32-13]
	_ = x[DataTypeEnum-14]
}

const (
	_DataType_name_0 = "Unknown"
	_DataType_name_1 = "DoubleFloatInt64Uint64Int32"
	_DataType_name_2 = "BoolString"
	_DataType_name_3 = "MessageBytesUint32Enum"
)

var (
	_DataType_index_1 = [...]uint8{0, 6, 11, 16, 22, 27}
	_DataType_index_2 = [...]uint8{0, 4, 10}
	_DataType_index_3 = [...]uint8{0, 7, 12, 18, 22}
)

func (i DataType) String() string {
	switch {
	case i == -1:
		return _DataType_name_0
	case 1 <= i && i <= 5:
		i -= 1
		return _DataType_name_1[_DataType_index_1[i]:_DataType_index_1[i+1]]
	case 8 <= i && i <= 9:
		i -= 8
		return _DataType_name_2[_DataType_index_2[i]:_DataType_index_2[i+1]]
	case 11 <= i && i <= 14:
		i -= 11
		return _DataType_name_3[_DataType_index_3[i]:_DataType_index_3[i+1]]
	default:
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
