# e01 with an alias: fields merge by response name.
query Alias {
    someNestedInterfaces {
        __typename
        otherInterfaces {
            __typename
        }
        ... on SomeNestedType2 {
            otherInterfaces {
                obj: someObject {
                    a
                }
            }
        }
        ... on SomeNestedType1 {
            otherInterfaces {
                obj: someObject {
                    a
                }
            }
        }
    }
}
