package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"

	"github.com/wundergraph/graphql-go-tools/execution/federationtesting/accounts/graph/generated"
	"github.com/wundergraph/graphql-go-tools/execution/federationtesting/accounts/graph/model"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return &model.User{
		ID:       "1234",
		Username: "Me",
		History:  histories,
		RealName: "User Usington",
	}, nil
}

// MeInterface is the resolver for the meInterface field.
func (r *queryResolver) MeInterface(ctx context.Context) (model.Identifiable, error) {
	return &model.User{
		ID:       "1234",
		Username: "Me",
		History:  histories,
		RealName: "User Usington",
	}, nil
}

// MeUnion is the resolver for the meUnion field.
func (r *queryResolver) MeUnion(ctx context.Context) (model.MeUnion, error) {
	return &model.User{
		ID:       "1234",
		Username: "Me",
		History:  histories,
		RealName: "User Usington",
	}, nil
}

// Identifiable is the resolver for the identifiable field.
func (r *queryResolver) Identifiable(ctx context.Context) (model.Identifiable, error) {
	return &model.User{
		ID:       "1234",
		Username: "Me",
		History:  histories,
		RealName: "User Usington",
	}, nil
}

// Histories is the resolver for the histories field.
func (r *queryResolver) Histories(ctx context.Context) ([]model.History, error) {
	return allHistories, nil
}

// Cat is the resolver for the cat field.
func (r *queryResolver) Cat(ctx context.Context) (*model.Cat, error) {
	return &model.Cat{
		Name: "Pepper",
	}, nil
}

// InterfaceUnion is the resolver for the interfaceUnion field.
func (r *queryResolver) InterfaceUnion(ctx context.Context, which model.Which) (model.Ab, error) {
	switch which {
	case model.WhichA:
		return &model.A{
			Name: "A",
		}, nil
	case model.WhichB:
		return &model.B{
			Name: "B",
		}, nil
	}
	return nil, fmt.Errorf("unknown which: %v", which)
}

// AbstractList is the resolver for the abstractList field.
func (r *queryResolver) AbstractList(ctx context.Context) ([]model.AbstractListItem, error) {
	return []model.AbstractListItem{
		&model.ConcreteListItem1{
			Obj: &model.SomeType1{
				Name:  "1",
				Age:   1,
				Names: []string{"1", "2"},
			},
		},
		&model.ConcreteListItem2{
			Obj: &model.SomeType2{
				Name:   "2",
				Height: 2.0,
				Names:  []string{"3", "4"},
			},
		},
	}, nil
}

// TitleName is the resolver for the titleName field.
func (r *queryResolver) TitleName(ctx context.Context) (*model.TitleName, error) {
	return &model.TitleName{
		Title: "Title",
		Name:  "Name",
		A:     "A",
		B:     "B",
		C:     "C",
	}, nil
}

// Cds is the resolver for the cds field.
func (r *queryResolver) Cds(ctx context.Context) ([]model.Cd, error) {
	return []model.Cd{
		&model.C{
			Name: &model.CDerObj{
				First:  "Leonie",
				Middle: "Johanna",
				Last:   "Neuse",
			},
		},
		&model.D{
			Name: &model.CDerObj{
				First:  "Jannik",
				Middle: "",
				Last:   "Neuse",
			},
		},
	}, nil
}

// OtherInterfaces is the resolver for the otherInterfaces field.
func (r *queryResolver) OtherInterfaces(ctx context.Context) ([]model.SomeInterface, error) {
	return []model.SomeInterface{
		&model.SomeType1{
			Name:  "1",
			Age:   1,
			Names: []string{"1", "2"},
			SomeObject: &model.SomeObject{
				A: "A",
				B: "B",
				C: "C",
			},
		},
		&model.SomeType2{
			Name:   "2",
			Height: 2.0,
			Names:  []string{"3", "4"},
			SomeObject: &model.SomeObject{
				A: "AA",
				B: "BB",
				C: "CC",
			},
		},
		&model.SomeType3{
			SomeObject: &model.SomeObject{
				A: "AAA",
				B: "BBB",
				C: "CCC",
			},
		},
	}, nil
}

// SomeNestedInterfaces is the resolver for the someNestedInterfaces field.
func (r *queryResolver) SomeNestedInterfaces(ctx context.Context) ([]model.SomeNestedInterface, error) {
	return []model.SomeNestedInterface{
		&model.SomeNestedType1{
			OtherInterfaces: []model.SomeInterface{
				&model.SomeType1{
					Name:  "1.1",
					Age:   1,
					Names: []string{"1.1", "1.2"},
					SomeObject: &model.SomeObject{
						A: "1.A",
						B: "1.B",
						C: "1.C",
					},
				},
				&model.SomeType2{
					Name:   "1.2",
					Height: 2.0,
					Names:  []string{"1.3", "1.4"},
					SomeObject: &model.SomeObject{
						A: "1.AA",
						B: "1.BB",
						C: "1.CC",
					},
				},
				&model.SomeType3{
					SomeObject: &model.SomeObject{
						A: "1.AAA",
						B: "1.BBB",
						C: "1.CCC",
					},
				},
			},
		},
		&model.SomeNestedType2{
			OtherInterfaces: []model.SomeInterface{
				&model.SomeType1{
					Name:  "2.1",
					Age:   1,
					Names: []string{"2.1", "2.2"},
					SomeObject: &model.SomeObject{
						A: "2.A",
						B: "2.B",
						C: "2.C",
					},
				},
				&model.SomeType2{
					Name:   "2.2",
					Height: 2.0,
					Names:  []string{"2.3", "2.4"},
					SomeObject: &model.SomeObject{
						A: "2.AA",
						B: "2.BB",
						C: "2.CC",
					},
				},
				&model.SomeType3{
					SomeObject: &model.SomeObject{
						A: "2.AAA",
						B: "2.BBB",
						C: "2.CCC",
					},
				},
			},
		},
	}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
