// Code generated by go-enum
// DO NOT EDIT!

package document

import (
	"fmt"
)

const (
	// OperationTypeUnknown is a OperationType of type Unknown
	OperationTypeUnknown OperationType = iota
	// OperationTypeQuery is a OperationType of type Query
	OperationTypeQuery
	// OperationTypeMutation is a OperationType of type Mutation
	OperationTypeMutation
	// OperationTypeSubscription is a OperationType of type Subscription
	OperationTypeSubscription
)

const _OperationTypeName = "unknownquerymutationsubscription"

var _OperationTypeMap = map[OperationType]string{
	0: _OperationTypeName[0:7],
	1: _OperationTypeName[7:12],
	2: _OperationTypeName[12:20],
	3: _OperationTypeName[20:32],
}

// String implements the Stringer interface.
func (x OperationType) String() string {
	if str, ok := _OperationTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("OperationType(%d)", x)
}

var _OperationTypeValue = map[string]OperationType{
	_OperationTypeName[0:7]:   0,
	_OperationTypeName[7:12]:  1,
	_OperationTypeName[12:20]: 2,
	_OperationTypeName[20:32]: 3,
}

// ParseOperationType attempts to convert a string to a OperationType
func ParseOperationType(name string) (OperationType, error) {
	if x, ok := _OperationTypeValue[name]; ok {
		return x, nil
	}
	return OperationType(0), fmt.Errorf("%s is not a valid OperationType", name)
}
