// Code generated by go-enum
// DO NOT EDIT!

package document

import (
	"fmt"
)

const (
	// ValueTypeVariable is a ValueType of type Variable
	ValueTypeVariable ValueType = iota
	// ValueTypeInt is a ValueType of type Int
	ValueTypeInt
	// ValueTypeFloat is a ValueType of type Float
	ValueTypeFloat
	// ValueTypeString is a ValueType of type String
	ValueTypeString
	// ValueTypeBoolean is a ValueType of type Boolean
	ValueTypeBoolean
	// ValueTypeNull is a ValueType of type Null
	ValueTypeNull
	// ValueTypeEnum is a ValueType of type Enum
	ValueTypeEnum
	// ValueTypeList is a ValueType of type List
	ValueTypeList
	// ValueTypeObject is a ValueType of type Object
	ValueTypeObject
)

const _ValueTypeName = "VariableIntFloatStringBooleanNullEnumListObject"

var _ValueTypeMap = map[ValueType]string{
	0: _ValueTypeName[0:8],
	1: _ValueTypeName[8:11],
	2: _ValueTypeName[11:16],
	3: _ValueTypeName[16:22],
	4: _ValueTypeName[22:29],
	5: _ValueTypeName[29:33],
	6: _ValueTypeName[33:37],
	7: _ValueTypeName[37:41],
	8: _ValueTypeName[41:47],
}

// String implements the Stringer interface.
func (x ValueType) String() string {
	if str, ok := _ValueTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("ValueType(%d)", x)
}

var _ValueTypeValue = map[string]ValueType{
	_ValueTypeName[0:8]:   0,
	_ValueTypeName[8:11]:  1,
	_ValueTypeName[11:16]: 2,
	_ValueTypeName[16:22]: 3,
	_ValueTypeName[22:29]: 4,
	_ValueTypeName[29:33]: 5,
	_ValueTypeName[33:37]: 6,
	_ValueTypeName[37:41]: 7,
	_ValueTypeName[41:47]: 8,
}

// ParseValueType attempts to convert a string to a ValueType
func ParseValueType(name string) (ValueType, error) {
	if x, ok := _ValueTypeValue[name]; ok {
		return x, nil
	}
	return ValueType(0), fmt.Errorf("%s is not a valid ValueType", name)
}
