// Code generated by "stringer -type=StoreDecision -linecomment -output=storedecision_string.go"; DO NOT EDIT.

package caching

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StoreDecisionNone-0]
	_ = x[StoreDecisionStored-1]
	_ = x[StoreDecisionFetchFailed-2]
	_ = x[StoreDecisionResponseErrors-3]
	_ = x[StoreDecisionInvalidResponse-4]
	_ = x[StoreDecisionInvalidCacheControl-5]
	_ = x[StoreDecisionNoStore-6]
	_ = x[StoreDecisionNoCache-7]
	_ = x[StoreDecisionNoDirective-8]
	_ = x[StoreDecisionNoLifetime-9]
	_ = x[StoreDecisionUnusableVary-10]
	_ = x[StoreDecisionPrivateWithoutID-11]
	_ = x[StoreDecisionNoEntity-12]
}

const _StoreDecision_name = "nonestoredfetch_failedresponse_errorsinvalid_responseinvalid_cache_controlno_storeno_cacheno_directiveno_lifetimeunusable_varyprivate_without_idno_entity"

var _StoreDecision_index = [...]uint8{0, 4, 10, 22, 37, 53, 74, 82, 90, 102, 113, 126, 144, 153}

func (i StoreDecision) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StoreDecision_index)-1 {
		return "StoreDecision(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StoreDecision_name[_StoreDecision_index[idx]:_StoreDecision_index[idx+1]]
}
