package plan

import (
	"strconv"

	"github.com/wundergraph/graphql-go-tools/v2/pkg/ast"
)

// upstreamFieldMergingAliasPrefix is used in aliases generated by the planner to disambiguate
// fields which share a response name across concrete members of an abstract type,
// but differ in nullability in a subgraph schema (e.g. User.id: ID! vs Admin.id: ID).
// Subgraphs reject such selection sets as failing field merging validation,
// and the spec suggested remedy is aliasing:
//
//	accounts { ... on User { __internal_merge_User_id: id } ... on Admin { __internal_merge_Admin_id: id } }
//
// The aliased field refs are tracked in fieldMergingAliasRefs, and the original response name
// is restored when building the resolve tree (see Visitor.EnterField).
const upstreamFieldMergingAliasPrefix = "__internal_merge_"

// memberField is a field selected on a concrete member of an abstract type
type memberField struct {
	typeName  string
	fieldRef  int
	fieldName string
}

// aliasConflictingMemberFields adds planner generated aliases to the fields of concrete members
// of an abstract type selection which would fail field merging validation on a subgraph.
// It reports whether any field was aliased - the caller has to treat this as a selection rewrite,
// as the response name based paths of the field children have changed.
func (c *nodeSelectionVisitor) aliasConflictingMemberFields(fieldRef int) (aliased bool) {
	selectionSetRef, ok := c.operation.FieldSelectionSet(fieldRef)
	if !ok {
		return false
	}

	inlineFragmentSelectionRefs := c.operation.SelectionSetInlineFragmentSelections(selectionSetRef)
	if len(inlineFragmentSelectionRefs) < 2 {
		return false
	}

	// Collect fields of the concrete member fragments grouped by response name (alias or field name).
	// Only concrete members are mutually exclusive at runtime - interface fragments could overlap.
	// The grouping key is the response name, not the schema field name: field merging validation on
	// a subgraph is keyed on the response name, and a client alias is copied onto every member when a
	// single abstract selection is flattened (e.g. `account { x: id }` becomes
	// `... on User { x: id } ... on Admin { x: id }`), so a user alias can still collide.
	// takenResponseNames tracks the response names already present in each member fragment so a
	// generated alias can be made collision-free against sibling selections.
	fieldsByResponseName := make(map[string][]memberField, 2)
	takenResponseNames := make(map[string]map[string]struct{}, 2)
	for _, inlineFragmentSelectionRef := range inlineFragmentSelectionRefs {
		inlineFragmentRef := c.operation.Selections[inlineFragmentSelectionRef].Ref
		typeName := c.operation.InlineFragmentTypeConditionNameString(inlineFragmentRef)

		node, exists := c.definition.NodeByNameStr(typeName)
		if !exists || node.Kind != ast.NodeKindObjectTypeDefinition {
			continue
		}

		fragmentSelectionSetRef, ok := c.operation.InlineFragmentSelectionSet(inlineFragmentRef)
		if !ok {
			continue
		}

		taken := takenResponseNames[typeName]
		if taken == nil {
			taken = make(map[string]struct{})
			takenResponseNames[typeName] = taken
		}

		for _, fieldSelectionRef := range c.operation.SelectionSetFieldSelections(fragmentSelectionSetRef) {
			memberFieldRef := c.operation.Selections[fieldSelectionRef].Ref
			fieldName := c.operation.FieldNameString(memberFieldRef)
			responseName := c.operation.FieldAliasOrNameString(memberFieldRef)
			taken[responseName] = struct{}{}

			if fieldName == typeNameField {
				continue
			}

			fieldsByResponseName[responseName] = append(fieldsByResponseName[responseName], memberField{typeName: typeName, fieldRef: memberFieldRef, fieldName: fieldName})
		}
	}

	for responseName, members := range fieldsByResponseName {
		if len(members) < 2 || !c.memberFieldsRequireAlias(members) {
			continue
		}

		for _, member := range members {
			alias := uniqueMergeAlias(upstreamFieldMergingAliasPrefix+member.typeName+"_"+responseName, takenResponseNames[member.typeName])
			c.operation.Fields[member.fieldRef].Alias = ast.Alias{
				IsDefined: true,
				Name:      c.operation.Input.AppendInputString(alias),
			}
			// preserve the original client-visible response name so it can be restored
			// when building the resolve tree (see Visitor.EnterField).
			c.fieldMergingAliasRefs[member.fieldRef] = []byte(responseName)
		}

		aliased = true
	}

	if aliased {
		// the response name based paths of the field children have changed,
		// so the subtree suggestions have to be recollected
		nestedFieldRefs := collectNestedFieldRefs(c.operation, selectionSetRef)
		c.addNewFieldRefs(nestedFieldRefs...)
		c.nodeSuggestions.RemoveSeenFields(nestedFieldRefs...)
	}

	return aliased
}

// memberFieldsRequireAlias reports whether the member field types differ only in nullability
// in any of the datasources upstream schemas. Genuinely incompatible types (e.g. Int vs String)
// are left untouched to surface through the regular validation instead of being masked by an alias.
func (c *nodeSelectionVisitor) memberFieldsRequireAlias(members []memberField) bool {
	for _, ds := range c.dataSources {
		upstreamSchema, ok := ds.UpstreamSchema()
		if !ok {
			continue
		}

		typeRefs := make([]int, 0, len(members))
		for _, member := range members {
			node, exists := upstreamSchema.NodeByNameStr(member.typeName)
			if !exists {
				continue
			}

			fieldDefinitionRef, exists := upstreamSchema.NodeFieldDefinitionByName(node, []byte(member.fieldName))
			if !exists {
				continue
			}

			typeRefs = append(typeRefs, upstreamSchema.FieldDefinitionType(fieldDefinitionRef))
		}

		if fieldTypesDifferOnlyInNullability(upstreamSchema, typeRefs) {
			return true
		}
	}

	return false
}

// uniqueMergeAlias returns candidate if it does not collide with any response name already
// present in the member fragment, otherwise it appends an incrementing suffix until it is unique.
// The chosen name is recorded in taken so subsequent generated aliases stay collision-free too.
func uniqueMergeAlias(candidate string, taken map[string]struct{}) string {
	if taken == nil {
		return candidate
	}

	name := candidate
	for i := 1; ; i++ {
		if _, exists := taken[name]; !exists {
			taken[name] = struct{}{}
			return name
		}
		name = candidate + "_" + strconv.Itoa(i)
	}
}

func fieldTypesDifferOnlyInNullability(schema *ast.Document, typeRefs []int) bool {
	differs := false
	for i := range typeRefs {
		for j := i + 1; j < len(typeRefs); j++ {
			if schema.TypesAreEqualDeep(typeRefs[i], typeRefs[j]) {
				continue
			}
			if !schema.TypesAreCompatibleIgnoringNullability(typeRefs[i], typeRefs[j]) {
				return false
			}
			differs = true
		}
	}

	return differs
}
