package plan

import (
	"github.com/wundergraph/graphql-go-tools/v2/pkg/ast"
)

// upstreamFieldMergingAliasPrefix is used in aliases generated by the planner to disambiguate
// fields which share a response name across concrete members of an abstract type,
// but differ in nullability in a subgraph schema (e.g. User.id: ID! vs Admin.id: ID).
// Subgraphs reject such selection sets as failing field merging validation,
// and the spec suggested remedy is aliasing:
//
//	accounts { ... on User { __internal_merge_User_id: id } ... on Admin { __internal_merge_Admin_id: id } }
//
// The aliased field refs are tracked in fieldMergingAliasRefs, and the original response name
// is restored when building the resolve tree (see Visitor.EnterField).
const upstreamFieldMergingAliasPrefix = "__internal_merge_"

// memberField is a field selected on a concrete member of an abstract type
type memberField struct {
	typeName string
	fieldRef int
}

// aliasConflictingMemberFields adds planner generated aliases to the fields of concrete members
// of an abstract type selection which would fail field merging validation on a subgraph.
// It reports whether any field was aliased - the caller has to treat this as a selection rewrite,
// as the response name based paths of the field children have changed.
func (c *nodeSelectionVisitor) aliasConflictingMemberFields(fieldRef int) (aliased bool) {
	selectionSetRef, ok := c.operation.FieldSelectionSet(fieldRef)
	if !ok {
		return false
	}

	inlineFragmentSelectionRefs := c.operation.SelectionSetInlineFragmentSelections(selectionSetRef)
	if len(inlineFragmentSelectionRefs) < 2 {
		return false
	}

	// collect fields of the concrete member fragments by response name.
	// Only concrete members are mutually exclusive at runtime - interface fragments could overlap.
	// A field with an alias owns its response name, so it could not conflict.
	fieldsByName := make(map[string][]memberField, 2)
	for _, inlineFragmentSelectionRef := range inlineFragmentSelectionRefs {
		inlineFragmentRef := c.operation.Selections[inlineFragmentSelectionRef].Ref
		typeName := c.operation.InlineFragmentTypeConditionNameString(inlineFragmentRef)

		node, exists := c.definition.NodeByNameStr(typeName)
		if !exists || node.Kind != ast.NodeKindObjectTypeDefinition {
			continue
		}

		fragmentSelectionSetRef, ok := c.operation.InlineFragmentSelectionSet(inlineFragmentRef)
		if !ok {
			continue
		}

		for _, fieldSelectionRef := range c.operation.SelectionSetFieldSelections(fragmentSelectionSetRef) {
			memberFieldRef := c.operation.Selections[fieldSelectionRef].Ref
			fieldName := c.operation.FieldNameString(memberFieldRef)
			if fieldName == typeNameField || c.operation.FieldAliasIsDefined(memberFieldRef) {
				continue
			}

			fieldsByName[fieldName] = append(fieldsByName[fieldName], memberField{typeName: typeName, fieldRef: memberFieldRef})
		}
	}

	for fieldName, members := range fieldsByName {
		if len(members) < 2 || !c.memberFieldsRequireAlias(fieldName, members) {
			continue
		}

		for _, member := range members {
			c.operation.Fields[member.fieldRef].Alias = ast.Alias{
				IsDefined: true,
				Name:      c.operation.Input.AppendInputString(upstreamFieldMergingAliasPrefix + member.typeName + "_" + fieldName),
			}
			c.fieldMergingAliasRefs[member.fieldRef] = struct{}{}
		}

		aliased = true
	}

	if aliased {
		// the response name based paths of the field children have changed,
		// so the subtree suggestions have to be recollected
		nestedFieldRefs := collectNestedFieldRefs(c.operation, selectionSetRef)
		c.addNewFieldRefs(nestedFieldRefs...)
		c.nodeSuggestions.RemoveSeenFields(nestedFieldRefs...)
	}

	return aliased
}

// memberFieldsRequireAlias reports whether the member field types differ only in nullability
// in any of the datasources upstream schemas. Genuinely incompatible types (e.g. Int vs String)
// are left untouched to surface through the regular validation instead of being masked by an alias.
func (c *nodeSelectionVisitor) memberFieldsRequireAlias(fieldName string, members []memberField) bool {
	fieldNameBytes := []byte(fieldName)

	for _, ds := range c.dataSources {
		upstreamSchema, ok := ds.UpstreamSchema()
		if !ok {
			continue
		}

		typeRefs := make([]int, 0, len(members))
		for _, member := range members {
			node, exists := upstreamSchema.NodeByNameStr(member.typeName)
			if !exists {
				continue
			}

			fieldDefinitionRef, exists := upstreamSchema.NodeFieldDefinitionByName(node, fieldNameBytes)
			if !exists {
				continue
			}

			typeRefs = append(typeRefs, upstreamSchema.FieldDefinitionType(fieldDefinitionRef))
		}

		if fieldTypesDifferOnlyInNullability(upstreamSchema, typeRefs) {
			return true
		}
	}

	return false
}

func fieldTypesDifferOnlyInNullability(schema *ast.Document, typeRefs []int) bool {
	differs := false
	for i := range typeRefs {
		for j := i + 1; j < len(typeRefs); j++ {
			if schema.TypesAreEqualDeep(typeRefs[i], typeRefs[j]) {
				continue
			}
			if !schema.TypesAreCompatibleIgnoringNullability(typeRefs[i], typeRefs[j]) {
				return false
			}
			differs = true
		}
	}

	return differs
}
