package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/wundergraph/graphql-go-tools/examples/federation/reviews/graph/generated"
	"github.com/wundergraph/graphql-go-tools/examples/federation/reviews/graph/model"
)

// FindProductByUpc is the resolver for the findProductByUpc field.
func (r *entityResolver) FindProductByUpc(ctx context.Context, upc string) (*model.Product, error) {
	var productReviews []*model.Review
	for _, review := range reviews {
		if review.Product.Upc == upc {
			productReviews = append(productReviews, review)
		}
	}

	return &model.Product{
		Upc:     upc,
		Reviews: productReviews,
	}, nil
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	var res []*model.Review

	for _, review := range reviews {
		if review.Author.ID == id {
			res = append(res, review)
		}
	}

	return &model.User{
		Reviews: res,
	}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
