// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Attachment interface {
	IsAttachment()
}

type Comment interface {
	IsComment()
	GetUpc() string
	GetBody() string
}

type Iface interface {
	IsIface()
	GetSubject() string
}

type Cat struct {
	Name string `json:"name"`
}

type DetatchedQuestion struct {
	Upc  string `json:"upc"`
	Body string `json:"body"`
}

func (DetatchedQuestion) IsComment()           {}
func (this DetatchedQuestion) GetUpc() string  { return this.Upc }
func (this DetatchedQuestion) GetBody() string { return this.Body }

type OtherQuestion struct {
	Upc  string `json:"upc"`
	Body string `json:"body"`
}

func (OtherQuestion) IsComment()           {}
func (this OtherQuestion) GetUpc() string  { return this.Upc }
func (this OtherQuestion) GetBody() string { return this.Body }

type Question struct {
	Upc     string `json:"upc"`
	Body    string `json:"body"`
	Subject string `json:"subject"`
}

func (Question) IsComment()           {}
func (this Question) GetUpc() string  { return this.Upc }
func (this Question) GetBody() string { return this.Body }

func (Question) IsIface()                {}
func (this Question) GetSubject() string { return this.Subject }

func (Question) IsAttachment() {}

type Rating struct {
	Upc   string `json:"upc"`
	Body  string `json:"body"`
	Score int    `json:"score"`
}

func (Rating) IsComment()           {}
func (this Rating) GetUpc() string  { return this.Upc }
func (this Rating) GetBody() string { return this.Body }

func (Rating) IsAttachment() {}

type Video struct {
	Upc     string  `json:"upc"`
	Size    float64 `json:"size"`
	Subject string  `json:"subject"`
}

func (Video) IsIface()                {}
func (this Video) GetSubject() string { return this.Subject }

func (Video) IsAttachment() {}
