on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: |
            graphql-go-tools
          permission-actions: write
          permission-contents: write
          permission-pull-requests: write
          permission-workflows: write

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: release-please-manifest.json
