name: v1-ci
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'v2/**'
      - '.github/workflows/v2.yml'
      - 'go.work'
      - 'go.work.sum'
  push:
    branches:
      - master
    paths-ignore:
      - 'v2/**'
      - '.github/workflows/v2.yml'
      - 'go.work'
      - 'go.sum'
jobs:
  test:
    name: Build and test (go ${{ matrix.go }} / ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ '1.19', '1.20' ]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ^${{ matrix.go }}
        id: go
      - name: CI
        run: make ci
      - name: Run tests under race detector
        if: runner.os != 'Windows' # These are very slow on Windows, skip them
        run: make test-race

  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: ^1.20
      - name: Run linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.2
          args: --timeout=3m
  ci:
    name: CI Success
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
